### ISSUE TITLE
License is MIT, but readme stipulates "personal use" in disclaimer.

### ISSUE THREAD

**Issue by jhlothamer** [fenix-hub/godot-engine.easy-charts#24]
You're disclaimer is at odds with the MIT license you have chosen for your project.  With MIT users can use your project in their commercial products. Peroid.  Remove the "personal use" verbage in your readme or change the license this project is listed under.  If you do this later option, you should also update the license listed in the Godot asset library.  Otherwise, I see no reason for anyone to adhere to your "personal use" intention.

**Comment by fenix-hub** [comment]
Hi @jhlothamer ,
I thought it was pretty clear that the "personal use" inside the Readme does not refer to how to use the plugin in their products, but just that, quote:
> This addon was built for a personal use intention. It was released as an open source plugin in the hope that it could be useful to the Godot Engine Community.
Also, as the same Readme mentions:
> As a "work in progress" project, there is no warranty for any eventual issue and bug that may broke your project.
I don't assume any responsibility for possible corruptions of your project. It is always advisable to keep a copy of your project and check any changes you make in your Github repository.

It just means that, since the plugin **was built** for personal usage and not for commercial purpose / framework projects, I'm not responsible if it will break your project or will not receive immedate updates / supports.

Can't see any mention on how to use this plugin in commercial products, instead that's why there is a License for that.
I can't see why I should have shared this repository public here on Github and still help people out on Discord if I wanted to keep it "personal" in legal/licensing terms. 

If you think that this is still not clear, please help me reformulate the sentence in the Readme in a more understandable way, since it is the first time a user adresses this problem.
Have a nice day.
