### ISSUE TITLE
[BUG] Samples are retained in `Function` objects, despite `max_samples` being set.

### ISSUE THREAD

**Issue by addmix** [fenix-hub/godot-engine.easy-charts#83]
Samples omitted by `ChartProperties.max_samples` are not freed from memory.

![image](https://github.com/fenix-hub/godot-engine.easy-charts/assets/38119387/ae158a47-e8ba-4dff-8ef7-764c5edaef17)

Values should also be removed from the Function objects as well.

**Comment by fenix-hub** [comment]
Although freeing the arrays would make memory more stable, removing values from the `x` and `y` arrays in the Chart script will make you lose all your first `n` values inside the Function object you are plotting.
`x` and `y` values are passed from the `Function` object to the `Chart` and `FunctionPlotter` classes by reference, as well as when you provide your `x` and `y` arrays to the `Function` object without cloning. So removing at any step a value from those array would make you lose them in your own data in your own arrays. 
Since I don't want to interfere with user's data, if you care more about performances than losing your runtime data I would suggest instead to achieve the same goal by calling the `Function.remove_point(0)` method before/after adding a new point.
Does it make sense to you?

**Comment by addmix** [comment]
Makes sense.
